BoomarkUsecase 설계 추가
f-lab-edu/iTime pull request #56
Opened 2023-11-19 13:07 UTC by sanghun0724

## Motivation ⭐️

- Usecase 기능 추가 필요

<br>

## Key Changes 🔑

- usecase 설계 및 추가

<br>

## To Reviewers 🙏

```
  /// 즐겨찾기 저장 - 갈아끼우는거 (update)
  func updateBookmarks() -> Single<Void>
  /// 즐겨찾기 기존에꺼에서 더하기 (add or append) (6개보다 작아야함)
  func appendBookmark() -> Single<Void>
  /// 즐겨찾기 기존에꺼에서 삭제 (remove at) (0개보다 커야함)
  func removeBookmark() -> Single<Void>
  /// 즐겨찾기 전체 불러오기 (Read)
  func bookmarks() -> Single<[Bookmark]>
```
전체 앱에서 즐겨찾기의 "행동"이 필요한 목록입니다.

2023-11-19 13:49 UTC, sanghun0724 commented on iTime/Domain/Sources/BookmarkUsecase/BookmarkUsecase.swift
> +  associatedtype Item
+) usecase의 유연성을 좀 더 확대해보려고 associatedType을 사용해보았습니다.

2023-11-20 14:04 UTC, f-lab-max commented on iTime/Domain/Sources/BookmarkUsecaseImpl/BookmarkUsecaseImpl.swift
> +public final class BookmarkUsecaseImpl: BookmarkUsecase {
final 사용 👍👍

2023-11-20 14:05 UTC, f-lab-max commented on iTime/Domain/Sources/BookmarkUsecase/BookmarkUsecase.swift
> +  func remove(by bookmark: Bookmark) -> Single<Void>
by 전치사 사용이 적절한가요? 의미 전달이 잘 안되는거 같습니다.
좀 더 명확한 의미 전달을 할 수 있는 네이밍이 필요해보입니다.

2023-11-20 14:06 UTC, f-lab-max commented on iTime/Feature/Sources/StartImpl/LogEntryCreationImpl/BookmarkEditor/BookmarkEditorBuilder.swift
> +  var bookmarkUsecase: any BookmarkUsecase { get }
`any`는 왜 필요한가요?

2023-11-20 14:08 UTC, f-lab-max commented on iTime/iTime.xcodeproj/project.pbxproj
> +		DE7CDC012B0B5A96009824D1 /* BookmarkUsecaseImpl in Frameworks */ = {isa = PBXBuildFile; productRef = DE7CDC002B0B5A96009824D1 /* BookmarkUsecaseImpl */; };
예전에도 언급했었던 것인데, 개발자가 여럿일 경우, 또는 상헌님이 여러 기능을 동시에 개발한다면 기능마다 Usecase를 추가하게 될텐데, xcodeproj 파일이 수정되면 컨플릿이 일어나서 '병렬 개발' 생산성에 큰 영향을 미칠거 같습니다. 어떻게 개선할 수 있을지 계속 고민바랍니다ㅎㅎ

2023-11-20 14:13 UTC, f-lab-max commented on iTime/Domain/Sources/BookmarkUsecaseImpl/BookmarkUsecaseImpl.swift
> +  private let bookmarkRepository: Any
👍 이런식으로 아직 존재하지 않는 의존성을 미리 선언해놓고 BookmarkUsecaseImpl을 만든게 아주 좋은거 같습니다.

조금만 더 개선해본다면 이왕 이 PR은 BookmarkUsecase, Impl 객체 전부 구현없이 선언만 해놓는 작업인데, BookmarkRepository도 그냥 프로토콜 선언만 해놓는 것까지 포함시켜도 괜찮지 않을까 싶습니다. PR 크기에도 아직 여유가 있고, 어차피 구현 코드는 없어서 리뷰어 부하도 적고요.

아무튼, PR 사이즈나 PR 쪼개는 단위가 정말 좋아지고 있습니다. 💯

2023-11-20 14:13 UTC, f-lab-max approved these changes

2023-11-20 14:14 UTC, f-lab-max requested changes
BookmarkUsecase 함수 네이밍 개선 필요

2023-11-21 14:32 UTC, sanghun0724 commented on iTime/Domain/Sources/BookmarkUsecase/BookmarkUsecase.swift
> +  func remove(by bookmark: Bookmark) -> Single<Void>
수정해보았습니다

2023-11-21 14:32 UTC, sanghun0724 commented on iTime/Feature/Sources/StartImpl/LogEntryCreationImpl/BookmarkEditor/BookmarkEditorBuilder.swift
> +  var bookmarkUsecase: any BookmarkUsecase { get }
associatedtype으로 어케어케 해보려다 그만.. 뺴는걸 깜빡했네요. 감사합니다!

2023-11-21 14:33 UTC, sanghun0724 commented on iTime/iTime.xcodeproj/project.pbxproj
> +		DE7CDC012B0B5A96009824D1 /* BookmarkUsecaseImpl in Frameworks */ = {isa = PBXBuildFile; productRef = DE7CDC002B0B5A96009824D1 /* BookmarkUsecaseImpl */; };
넵..!

2023-11-21 14:35 UTC, sanghun0724 commented on iTime/Domain/Sources/BookmarkUsecaseImpl/BookmarkUsecaseImpl.swift
> +  private let bookmarkRepository: Any
아하 넵. 알겠습니다. 아무래도 저도 추상화 프로토콜 들은 미리미리 먼저 리뷰를 받아놓을까 고민되더라고요. 
그러면 feature branch를 chaining 안하더라도 abstract dependency 가지고 병렬 작업이 가능해지니까요

2023-11-21 16:14 UTC, f-lab-max commented on iTime/Domain/Sources/BookmarkUsecaseImpl/BookmarkUsecaseImpl.swift
> +  private let bookmarkRepository: Any
good

2023-11-21 16:16 UTC, f-lab-max commented on iTime/Domain/Sources/BookmarkUsecase/BookmarkUsecase.swift
> +  func removeBookmark(_ bookmark: Bookmark) -> Single<Void>
nit: 저라면 Bookmark도 뺄거 같습니다. 사용할때를 상상해보면,

```swift
let newBookmark = ...
bookmarkUsecase.appendBookmark(newBookmark)
```

이렇게 될텐데, 함수명에 Bookmark가 불필요해보입니다.
```swift
bookmarkUsecase.append(newBookmark)
```

이게 좀 더 자연스럽게 문장처럼 읽히지 않을까요

2023-11-21 16:17 UTC, f-lab-max approved these changes

2023-11-21 16:17 UTC, f-lab-max approved these changes

2023-11-21 23:24 UTC, sanghun0724 commented on iTime/Domain/Sources/BookmarkUsecase/BookmarkUsecase.swift
> +  func removeBookmark(_ bookmark: Bookmark) -> Single<Void>
으흠 그렇네요. 인터페이스만 보고 판단했었는데, 실제 사용할때도 고려를 했었어야 했네요..! 감사합니다

2023-11-22 12:35 UTC, merged