Bookmark repository 추가 및 Repository 패키지 구조 변경
f-lab-edu/iTime pull request #58
Opened 2023-11-21 14:41 UTC by sanghun0724

## Motivation ⭐️

- Bookmark Repository 
- proj 파일을 변경시키지 않기 위해 repositoy 폴더 구조 변경 필요

<br>

## Key Changes 🔑

- Bookmark Repository 추가 (+ single issue)
- 크게 Repository 구조는
-  NetworkRepository, 
- NetworkRepositoryImpl, 
- LocalDatabaseRepository,
-  LocalDatabaseRespositoryImpl 로  정리 

<br>

## To Reviewers 🙏

2023-11-21 16:24 UTC, f-lab-max commented on iTime/Platform/Sources/NetworkRepositoryImpl/BookmarkRepositoryImpl/BookmarkRepositoryImpl.swift
> +    .map { try! $0.decode()! }
`!` 는 쓰지 않는 습관을 들이길 추천합니다. 아무리 개발자가 크래시가 안날거라고 생각해도 꼭 나더라고요 ㅎㅎ. 안전한 코딩이 훨씬 좋습니다.

2023-11-21 16:41 UTC, f-lab-max commented on iTime/Platform/Sources/NetworkRepositoryImpl/BookmarkRepositoryImpl/BookmarkRepositoryImpl.swift
> +public final class BookmarkRepositoryImpl: FirestoreRepository, BookmarkRepository {
FirestoreRepository protocol extension으로 Firestore.firestore() 를 사용함으로써 코드 재사용을 하고자 하신거 같은데, 의존성 주입 원칙 관점에서 보면 volatile dependency(여기서는 Firestore)를 생성자 주입 안하고 static 멤버 변수로 접근해서 쓰는 것은 ambient context라는 안티패턴에 속합니다. BookmarkRepositoryImpl 의 생성자를 보면 아무런 파라미터가 없어 이 객체의 의존성이 뭔지 알수가 없고, protocol extension으로 Firestore가 숨어있습니다. 가급적 생성자 주입을 사용하여 정적으로 의존성을 정의하는 것이 코드 유지보수에 더 좋습니다.

ambient context가 문제되는 이유는
- 객체의 의존성이 숨어있다.
- 테스트 코드를 더 복잡하게 만든다.
- temporal coupling (의존성 주입과 사용 간에 타이밍 이슈)

하나 더, 상헌님이 protocol extension으로 구현해주신거는 "추상화의 default behavior를 제공했다" 라고 표현할수 있는데, 의존성 주입 관점에서 추상화의 default behavior를 제공해도 괜찮은 경우는 매우 제한적입니다. 
(1) volatile dependency에 의존하지 않는 경우, 또는 
(2) 인터페이스를 소유한 모듈 내에서 구현체도 소유할때 정도로 볼수 있습니다. 

FirestoreRepository의 default behavior인 경우 둘 다 위반이기 때문에 좋은 선택이 아닙니다.

2023-11-21 23:29 UTC, sanghun0724 commented on iTime/Platform/Sources/NetworkRepositoryImpl/BookmarkRepositoryImpl/BookmarkRepositoryImpl.swift
> +    .map { try! $0.decode()! }
쉽게 테스트하려다가 쓰던 코드가 남아버렸네요.. 체크 감사합니다!

2023-11-21 23:32 UTC, sanghun0724 commented on iTime/Platform/Sources/NetworkRepositoryImpl/BookmarkRepositoryImpl/BookmarkRepositoryImpl.swift
> +public final class BookmarkRepositoryImpl: FirestoreRepository, BookmarkRepository {
저도 관련해서 비슷한 생각을 하게 되었는데 
이번에 PR 날리면서 repository 테스트를 작성하려 하니 말씀하신 대로 
FirestoreRepository가 의존성 주입형태가 아니니 Mock객체를 만들수가 없더라고요. 
남겨주신 부분들 참고해서 리팩토링후 + 테스트 까지 다음 PR에 반영하도록 하겠습니다! 감사합니다

2023-11-22 20:25 UTC, nsoojin commented on iTime/Platform/Sources/NetworkRepository/BookmarkRepository/BookmarkRepository.swift
> +  func updateBookmarks(with bookmarks: [Bookmark], for userID: String) -> Single<Void>
메서드 주입을 해주는게 맞을까요? userID라는 의존성은 bookmarkrepository를 사용하는 객체가, bookmark 관련 CRUD를 할때 호출할 때마다 다르게 바꿔줘야하는 값인가요?

2023-11-22 20:28 UTC, nsoojin commented on iTime/Platform/Tests/NetworkRepositoryImplTests/BookmarkRepositoryImplTests.swift
> +    wait(for: [expectation], timeout: 1.5)
유닛 테스트에서 비동기성은 flakiness를 유발하는 1등 원인입니다. 게다가 "비동기성"은 implementation detail에 해당할때가 많습니다. 이를 숨길수 있다면 최선입니다. 저는 Combine으로만 해봤는데 후딱 검색해보니 Rx도 동기적으로 테스트하는 방법이 있는거 같습니다. 이를 찾아보고 적용해보는게 좋겠습니다.

2023-11-22 20:29 UTC, f-lab-max commented on iTime/Platform/Tests/NetworkRepositoryImplTests/BookmarkRepositoryImplTests.swift
> +    wait(for: [expectation], timeout: 1.5)
유닛 테스트에서 비동기성은 flakiness를 유발하는 1등 원인입니다. 게다가 "비동기성"은 implementation detail에 해당할때가 많습니다. 이를 숨길수 있다면 최선입니다. 저는 Combine으로만 해봤는데 후딱 검색해보니 Rx도 동기적으로 테스트하는 방법이 있는거 같습니다. 이를 찾아보고 적용해보는게 좋겠습니다.

2023-11-22 20:30 UTC, f-lab-max commented on iTime/Platform/Sources/NetworkRepository/BookmarkRepository/BookmarkRepository.swift
> +  func updateBookmarks(with bookmarks: [Bookmark], for userID: String) -> Single<Void>
userID를 메서드 주입을 해주는게 맞을까요? userID라는 의존성은 bookmarkrepository를 사용하는 객체가, bookmark 관련 CRUD를 할때 호출할 때마다 다르게 바꿔줘야하는 값인가요?

2023-11-23 17:09 UTC, f-lab-max requested changes

2023-11-23 17:09 UTC, f-lab-max commented on iTime/Platform/Sources/NetworkRepository/BookmarkRepository/Entities/Bookmark.swift
> +public struct Bookmark: Codable, Equatable {
`Equatable`: 테스트에만 필요한 코드가 프로덕션 코드에 들어가는건 좋지 않다고 생각합니다. 
만약 나중에 프로덕션에도 필요해서 넣을것이라면, title로 equality를 비교하는것에 의문이 가는데 같은 title을 가진 북마크를 가질수 없다는게 비즈니스 로직인건가요?

2023-11-24 00:19 UTC, sanghun0724 commented on iTime/Platform/Sources/NetworkRepository/BookmarkRepository/Entities/Bookmark.swift
> +public struct Bookmark: Codable, Equatable {
넵 일단은 기획상으로 활동의 구별은 "공백이없는 활동 Title String"으로 하자. 라고 정해졌지만, 아직 Equtable를 이용해서 만든 코드가 없긴 합니다. TestTarget에서 extension으로 빼도 상관은 없지만, 추가 될 코드라 겸사겸사(?) 수정 하였습니다.

2023-11-24 14:29 UTC, sanghun0724 commented on iTime/Platform/Sources/NetworkRepositoryImpl/BookmarkRepositoryImpl/BookmarkRepositoryImpl.swift
> +  private let userDefaultRepository: ReadOnlyUserDefaultRepository
저는 저를 못믿기 때문에..ㅋㅋ 말씀하신 구조로 변경해보았습니다~

2023-11-24 21:01 UTC, f-lab-max approved these changes

2023-11-24 23:58 UTC, merged