Feature/log history repo
f-lab-edu/iTime pull request #66
Opened 2023-11-26 10:06 UTC by sanghun0724

## Motivation ⭐️

- RxBlocking 방식도 알고보니 여전히 안좋은 테스트 코드 (비동기에 취약한) 방식 이여서 가상 scheduler 개념이 있는 RxTest로 테스트 방식 변경 하였습니다.
- TimeLog를 담당하는 repository 추가 필요
- 그에 따른 unit test 필요

<br>

## Key Changes 🔑

- RxBocking -> RxTest
- TimeLogHistoryRepository 추가
- TimeLogHistoryRepositoryImplTest 추가
- Mock 구조 변경  

<br>

## To Reviewers 🙏
테스트를 작성하다.. Bookmark Repository Test도 잘못 되었던 걸 깨달아서 같이 리팩토링 하다 보니 PR이 조금 커져버렸네요. (분리 할까 고민민하다.. 잘못된 결정을 내려버렸습니다)

앞으로는 PR이 짧더라도 그냥 나눌땐 확실히 나누는 식으로 가도록 하겠습니다..!

2023-11-27 13:52 UTC, f-lab-max requested changes
.

2023-11-27 13:52 UTC, f-lab-max commented on iTime/Domain/Sources/NetworkRepository/Entities/Coordinate2D.swift
> +  public static let empty: Coordinate2D = .init(latitude: 0.0, longitude: 0.0)
nit: empty 보단 zero가 더 의미적으로 적합하지 않나요?

2023-11-27 13:52 UTC, f-lab-max commented on iTime/Domain/Sources/NetworkRepository/Entities/BookmarkList.swift
> +public struct BookmarkList: Codable {
Domain에 repository interface를 합쳤으니 폴더 구조도 좀 정리하면 좋겠네요. Domain을 구성하는 큰 요소는 Entity, Usecase interface+implementation, 그리고 repository interface입니다.

이 3개가 잘 구분되고 모여있도록 하면 좋겠습니다. 특히 도메인 모델이 Repository 하위 폴더에 있는건 의아합니다.

2023-11-27 13:52 UTC, f-lab-max commented on iTime/Platform/Tests/NetworkRepositoryImplTests/BookmarkRepositoryImplTests.swift
> +    scheduler.scheduleAt(10) { [weak self] in
10이라는 매직넘버는 무슨 의미인가요?

2023-11-27 13:52 UTC, f-lab-max commented on iTime/Platform/Tests/NetworkRepositoryImplTests/BookmarkRepositoryImplTests.swift
> +    XCTAssertEqual(observer.events, [
무엇이 몇번 불렸는지 (행위) 보다는 상태값을 검증해야합니다. append를 테스트한다면 append를 한 이후에 bookmarks(list) 상태값을 검증하는게 핵심인데 그게 없네요

2023-11-27 13:52 UTC, f-lab-max commented on iTime/Platform/Sources/NetworkRepositoryImpl/BookmarkRepositoryImpl/BookmarkRepositoryImpl.swift
>        .map {  $0.filter { $0.title != bookmark.title } }
객체 equality를 이용하면 가독성이 조금 좋아질거 같습니다.

2023-11-27 13:52 UTC, f-lab-max commented on iTime/Platform/Tests/NetworkRepositoryImplTests/BookmarkRepositoryImplTests.swift
> +    XCTAssertEqual(observer.events, [
BookmarkRepositoryImplTests의 테스트들이 전부 이런식인거 같습니다. 행위보다는 상태 검증을 우선시 해주세요.

2023-11-27 13:52 UTC, f-lab-max commented on iTime/Platform/Tests/NetworkRepositoryImplTests/BookmarkRepositoryImplTests.swift
> +    let resultSubject = PublishSubject<Bool>()
테스트코드가 보일러플레이트가 많아서 번거로운거 같은데 이 방법 밖에 없나요? https://www.kodeco.com/7408-testing-your-rxswift-code?page=2# 여기 나와있는 방법이 좀 더 간결해보이는데 차이가 뭔지 궁금합니다.

2023-11-28 08:28 UTC, sanghun0724 commented on iTime/Domain/Sources/NetworkRepository/Entities/Coordinate2D.swift
> +  public static let empty: Coordinate2D = .init(latitude: 0.0, longitude: 0.0)
수정 하였습니다.

2023-11-28 08:30 UTC, sanghun0724 commented on iTime/Domain/Sources/NetworkRepository/Entities/BookmarkList.swift
> +public struct BookmarkList: Codable {
넵 좋습니다.
도메인 모델부분은 사실 네트워크 통신 DTO인데 네이밍을 잘못 지은것 같습니다. 변경하도록 하겠습니다.

2023-11-28 08:40 UTC, sanghun0724 commented on iTime/Domain/Sources/NetworkRepository/Entities/BookmarkList.swift
> +public struct BookmarkList: Codable {
그리고 지금 살짝 부자연스러운 부분이 도메인 모델인데, 그 이유가 네트워크 DTO랑 도메인 Entity랑 큰 차이가 없습니다.
파이어베이스로 그냥 제가 작업하다보니 Time값들도 사실 제가 그냥 String으로 upload하고 그값을 그대로 내려 받아서 쓰기때문에 중간에 Translate 같은 것을 할 이유가 없어서 살짝 둘의 경계가 애매합니다. (일단 중복되더라도 나눠놓기는 했습니다.)

2023-11-28 08:43 UTC, sanghun0724 commented on iTime/Platform/Tests/NetworkRepositoryImplTests/BookmarkRepositoryImplTests.swift
> +    scheduler.scheduleAt(10) { [weak self] in
특별한 의미가 없습니다. 이런 경우 1로 시작하는게 자연스러울까요?

2023-11-28 08:43 UTC, sanghun0724 commented on iTime/Platform/Tests/NetworkRepositoryImplTests/BookmarkRepositoryImplTests.swift
> +    XCTAssertEqual(observer.events, [
넵 확인했습니다.

2023-11-28 23:33 UTC, sanghun0724 commented on iTime/Platform/Tests/NetworkRepositoryImplTests/BookmarkRepositoryImplTests.swift
> +    let resultSubject = PublishSubject<Bool>()
일단 큰 차이는 없습니다.
다만, 저기에서는 ViewModel을 테스트 하고 Observable을 대상으로 하지만, 
제 테스트는 레포지토리를 테스트하고 Single을 대상으로 한다는 차이점이 있습니다. 따라 구현에도 차이가 나는것 같습니다.
저도 보일러플레이트가 너무 길어보여서 최대한 간결하게 쓰는 방식으로 한번 리팩토링 해보았습니다. 확인 부탁드립니다~

2023-11-28 23:35 UTC, sanghun0724 commented on iTime/Platform/Tests/NetworkRepositoryImplTests/BookmarkRepositoryImplTests.swift
> +    scheduler.scheduleAt(10) { [weak self] in
특별한 의미가 없는데 오용한것 같습니다. 수정하였습니다

2023-11-29 21:45 UTC, f-lab-max commented on iTime/Domain/Sources/NetworkRepository/Entities/BookmarkList.swift
> +public struct BookmarkList: Codable {
네트워크 DTO라면 Domain 계층이 아니라 그 아래 계층에 있어야 합니다.

2023-11-29 21:48 UTC, f-lab-max commented on iTime/Platform/Tests/NetworkRepositoryImplTests/BookmarkRepositoryImplTests.swift
> +    let resultSubject = PublishSubject<Bool>()
확인했습니다.

2023-12-01 15:18 UTC, sanghun0724 commented on iTime/Domain/Sources/NetworkRepository/Entities/BookmarkList.swift
> +public struct BookmarkList: Codable {
수정하여 반영하였습니다. 확인 부탁드립니다.!

반영 목록은
1. Model - Entities의 분리
2. 그에 따른 수정 사항들
- Translator 추가 
- 바뀐 모델들 모두 적용

2023-12-01 16:34 UTC, f-lab-max approved these changes
PR이 점점 커지고 있어서, 적당히 끊고 새로운 태스크는 새로운 PR로 하는게 좋겠습니다.

2023-12-01 16:36 UTC, f-lab-max commented on iTime/Platform/Sources/Translator/BookmarkTranslator.swift
> +public protocol BookmarkTranslator {
이 translator 라는 것이 volatile dependency인가요?

2023-12-01 23:37 UTC, sanghun0724 commented on iTime/Platform/Sources/Translator/BookmarkTranslator.swift
> +public protocol BookmarkTranslator {
아뇨. 생각해보니  stable dependency에 가깝습니다.  흐음... 이 부분 수정하여 다음 PR에 반영하도록 하겠습니다.

2023-12-01 23:39 UTC, merged